//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <NanoTimeKit/_RemoteOperation.h>

@class CLKComplication;

@interface _LocalizableSampleTemplateOperation : _RemoteOperation
{
    CLKComplication *_complication;
    CDUnknownBlockType _templateHandler;
}

@property(copy, nonatomic) CDUnknownBlockType templateHandler; // @synthesize templateHandler=_templateHandler;
// - (void).cxx_destruct;
- (void)activateWithClient:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (_Bool)canCoalesceWithOperation:(id)arg1;
- (id)initWithClientIdentifier:(id)arg1 appBundleIdentifier:(id)arg2 complication:(id)arg3;

@end

