//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

#import "CLKComplicationClientInvalidationObserver.h"

@class CLKComplicationClient, NSDate, NSMutableArray, NSString, NSTimer, NTKRemoteComplicationBudgetManager, NTKTaskScheduler, PCPersistentTimer, SPComplicationConnection, _RemoteOperation;

@interface _RemoteOperationQueue : NSObject <CLKComplicationClientInvalidationObserver>
{
    SPComplicationConnection *_complicationConnection;
    _RemoteOperation *_activeOperation;
    NSMutableArray *_queuedOperations;
    struct NSNumber *_waitForClientToken;
    CLKComplicationClient *_client;
    int _status;
    int _meteringType;
    _Bool _haveAlreadyPokedClientThisSession;
    _Bool _clientHasInitiatedOperationThisSession;
    _Bool _haveGotRequestedWakeDateThisSession;
    NSDate *_requestedWakeDate;
    NSTimer *_minimumWakeSessionTimer;
    NSTimer *_prolongWakeSessionTimer;
    NSTimer *_maximumWakeSessionTimer;
    double _nextBackoffInterval;
    PCPersistentTimer *_backoffTimer;
    NTKTaskScheduler *_taskScheduler;
    struct NSNumber *_beginWakeSessionLaterTaskToken;
    _Bool _shouldExtendSessionInsteadOfBegin;
    NSString *_clientIdentifier;
    NSString *_appBundleIdentifier;
    CDUnknownBlockType _sessionStartHandler;
    CDUnknownBlockType _sessionEndHandler;
    CDUnknownBlockType _deviceSwitchSessionEndHandler;
    CDUnknownBlockType _completionHandler;
    NTKRemoteComplicationBudgetManager *_budgetManager;
}

@property(nonatomic) _Bool shouldExtendSessionInsteadOfBegin; // @synthesize shouldExtendSessionInsteadOfBegin=_shouldExtendSessionInsteadOfBegin;
@property(retain, nonatomic) NTKRemoteComplicationBudgetManager *budgetManager; // @synthesize budgetManager=_budgetManager;
@property(copy, nonatomic) CDUnknownBlockType completionHandler; // @synthesize completionHandler=_completionHandler;
@property(copy, nonatomic) CDUnknownBlockType deviceSwitchSessionEndHandler; // @synthesize deviceSwitchSessionEndHandler=_deviceSwitchSessionEndHandler;
@property(copy, nonatomic) CDUnknownBlockType sessionEndHandler; // @synthesize sessionEndHandler=_sessionEndHandler;
@property(copy, nonatomic) CDUnknownBlockType sessionStartHandler; // @synthesize sessionStartHandler=_sessionStartHandler;
@property(readonly, nonatomic) NSString *appBundleIdentifier; // @synthesize appBundleIdentifier=_appBundleIdentifier;
@property(readonly, nonatomic) NSString *clientIdentifier; // @synthesize clientIdentifier=_clientIdentifier;
// - (void).cxx_destruct;
- (void)_scheduleTryToBeginWakeSessionTask;
- (void)_backoffTimerFired:(id)arg1;
- (void)_scheduleRetryAttemptAfterBackoff;
- (void)_cancelWakeSessionAndReschedule:(_Bool)arg1;
- (void)_maybeEndWakeSessionAndExit;
- (void)complicationClientInvalidated:(id)arg1;
- (void)_maximumSessionTimerFired;
- (void)_prolongSessionTimerFired;
- (void)_minimumSessionTimerFired;
- (void)_clearProlongSessionTimer;
- (void)_clearMaximumSessionTimer;
- (void)_clearMinimumSessionTimer;
- (void)_setMaximumSessionTimer;
- (void)_setProlongSessionTimer;
- (void)_setMinimumSessionTimer;
- (void)_updateMetering;
- (void)_endWakeSession;
- (void)_beginWakeSession;
- (void)_tryToBeginWakeSessionIfNecessary;
- (_Bool)_allEnqueuedOperationsAreDiscretionary;
- (void)_dequeueOperationIfPossible;
- (_Bool)isBeingDebugged;
- (_Bool)hasInitialSetupOperationsInFlight;
- (void)cancelAndRemoveOperationsPassingTest:(CDUnknownBlockType)arg1;
- (void)noteClientInitiatedOperation;
- (void)noteBudgetReset;
- (void)cancelWakeSession;
- (void)enqueueOperation:(id)arg1;
- (id)initWithClientIdentifier:(id)arg1 appBundleIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

