//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark Blocks

typedef void (^CDUnknownBlockType)(void); // return type and parameters are unknown

#pragma mark Named Structures

struct CATransform3D {
    float _field1;
    float _field2;
    float _field3;
    float _field4;
    float _field5;
    float _field6;
    float _field7;
    float _field8;
    float _field9;
    float _field10;
    float _field11;
    float _field12;
    float _field13;
    float _field14;
    float _field15;
    float _field16;
};

struct CGAffineTransform {
    float _field1;
    float _field2;
    float _field3;
    float _field4;
    float _field5;
    float _field6;
};

struct CGPathElement {
    int _field1;
    struct CGPoint *_field2;
};

struct CGPoint {
    float x;
    float y;
};

struct CGSize {
    float width;
    float height;
};

struct CGRect {
    struct CGPoint origin;
    struct CGSize size;
};

struct CGVector {
    float dx;
    float dy;
};

struct CLLocationCoordinate2D {
    double latitude;
    double longitude;
};

struct CharacterPoseSpecs {
    float bodyOffsetX;
    float footOffsetX;
    float headOffsetX;
};

struct CharacterStateSpecs {
    unsigned int bodyTexIdx;
    unsigned int minuteTexIdx;
    unsigned int hourArmOnLeftShoulder;
    float xFlipBody;
    float xFlipFoot;
    float xFlipFace;
    float xFlipMinuteHand;
    float xFlipHourHand;
    float leftShoulderX;
    float rightShoulderX;
    float minuteElbowBend;
    float hourElbowBend;
};

struct LabelPosition {
    struct CGPoint _field1;
    int _field2;
    int _field3;
};

struct NSArray {
    Class _field1;
};

struct NSNumber {
    Class _field1;
};

struct NTKAstronomyFaceViewAnimationPose {
    float _field1;
    float _field2;
    float _field3;
    float _field4;
    float _field5;
    float _field6;
    float _field7;
};

struct NTKAstronomyInteractionSettings {
    float _field1;
    float _field2;
    float _field3;
    float _field4;
};

struct NUProgram {
    unsigned int program;
    int uniforms[11];
};

struct NTKCharacterPrograms {
    struct NUProgram programs[6];
};

struct NUMemFile {
    int descriptor;
    int length;
    char *mapping;
};

struct RingLayout {
    float bottomEdgeInset;
    float leftEdgeInset;
    float diameter;
    float thickness;
    float interspacing;
};

struct UIEdgeInsets {
    float top;
    float left;
    float bottom;
    float right;
};

//struct _NSRange {
//    unsigned int _field1;
//    unsigned int _field2;
//};

#pragma mark Typedef'd Structures

typedef struct {
    _Bool isComplexBackground;
    _Bool isColoredText;
    float textHue;
    float textSaturation;
    float textBrightness;
    float bgHue;
    float bgSaturation;
    float bgBrightness;
    float shadowHue;
    float shadowSaturation;
    float shadowBrightness;
} CDStruct_77693742;

typedef struct {
    float _field1;
    float _field2;
    float _field3;
} CDStruct_869f9c67;

typedef struct {
    long long value;
    int timescale;
    unsigned int flags;
    long long epoch;
} CDStruct_1b6d18a9;

typedef struct {
    float _field1;
    float _field2;
    float _field3;
    float _field4;
    float _field5;
    float _field6;
    float _field7;
    float _field8;
    float _field9;
    float _field10;
    float _field11;
    float _field12;
    struct UIEdgeInsets _field13;
} CDStruct_4eca2615;

#pragma mark Named Unions

union _GLKMatrix4 {
    struct {
        float m00;
        float m01;
        float m02;
        float m03;
        float m10;
        float m11;
        float m12;
        float m13;
        float m20;
        float m21;
        float m22;
        float m23;
        float m30;
        float m31;
        float m32;
        float m33;
    } ;
    float m[16];
};

union _GLKVector2 {
    struct {
        float x;
        float y;
    } ;
    struct {
        float s;
        float t;
    } ;
    float v[2];
};

union _GLKVector3 {
    CDStruct_869f9c67 _field1;
    CDStruct_869f9c67 _field2;
    CDStruct_869f9c67 _field3;
    float _field4[3];
};

