//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <NanoTimeKit/NTKComplicationController.h>

@interface NTKAlarmComplicationController : NTKComplicationController
{
    struct NSNumber *_timerToken;
    struct {
        unsigned int wantsName:1;
    } _displayFlags;
}

+ (_Bool)_acceptsComplicationType:(unsigned int)arg1;
// - (void).cxx_destruct;
- (void)_timerTick;
- (void)_timeOrLocaleChanged;
- (void)_handleAlarmsDidChange;
- (id)_dateForAlarm:(id)arg1;
- (void)_forceUpdateDisplay;
- (void)_updateDisplay;
- (id)complicationApplicationIdentifier;
- (void)performTapAction;
- (void)setDataMode:(int)arg1 forDisplayWrapper:(id)arg2;
- (_Bool)hasTapAction;
- (void)_configureForLegacyDisplay:(id)arg1;
- (void)_deactivate;
- (void)_activate;

// Remaining properties
@property(readonly, nonatomic) __weak id <NTKAlarmComplicationDisplay> legacyDisplay; // @dynamic legacyDisplay;

@end

