//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

#import "NSSecureCoding.h"

@class NSMutableDictionary, NSMutableSet, NSString;

@interface NTKComplicationSampleData : NSObject <NSSecureCoding>
{
    NSMutableDictionary *_familyToTemplate;
    NSMutableSet *_supportedFamilies;
    NSString *_clientID;
    NSString *_applicationID;
}

+ (_Bool)supportsSecureCoding;
@property(copy) NSString *applicationID; // @synthesize applicationID=_applicationID;
@property(copy) NSString *clientID; // @synthesize clientID=_clientID;
// - (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)supportedFamilies;
- (id)loadedFamilies;
- (void)setTemplate:(id)arg1 forFamily:(int)arg2;
- (id)templateForFamily:(int)arg1;
- (id)initWithSupportedFamilies:(id)arg1;

@end

