//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@interface CLKDate : NSDate

+ (id)complicationDate;
+ (id)complicationDateWithTimeIntervalSinceNow:(double)arg1;
+ (id)date;
+ (id)dateWithTimeIntervalSinceNow:(double)arg1;
+ (double)timeIntervalSinceReferenceDate;
+ (id)unmodifiedDate;
+ (id)unmodifiedDateWithTimeIntervalSinceNow:(double)arg1;

- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithTimeIntervalSinceNow:(double)arg1;
- (id)initWithTimeIntervalSinceReferenceDate:(double)arg1;
- (double)timeIntervalSinceNow;

@end

@interface NTKDate : CLKDate
{
}

+ (id)faceDateWithTimeIntervalSinceNow:(double)arg1;
+ (id)faceDate;

@end

