//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

#import <Foundation/Foundation.h>
#import "NSSecureCoding.h"

@class NSMutableDictionary, NSString;

@interface NTKFaceConfiguration : NSObject <NSCopying, NSSecureCoding>
{
    NSMutableDictionary *_complications;
    NSMutableDictionary *_editModeConfigurations;
    NSString *_name;
}

+ (_Bool)supportsSecureCoding;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
// - (void).cxx_destruct;
- (void)_applyComplicationsDescription:(id)arg1;
- (void)_applyCustomizationDescription:(id)arg1 editModeMapping:(id)arg2;
- (id)initWithJSONDictionary:(id)arg1 editModeMapping:(id)arg2;
- (void)addConfigurationKeysToJSONDictionary:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (unsigned int)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)_enumerateComplicationsWithBlock:(CDUnknownBlockType)arg1;
- (void)_enumerateEditModeConfigurationsWithBlock:(CDUnknownBlockType)arg1;
- (void)appendEditModesToDailySnapshotKey:(id)arg1;
- (id)description;
- (void)setComplication:(id)arg1 forSlot:(id)arg2;
- (id)complicationForSlot:(id)arg1;
- (void)setOption:(id)arg1 forCustomEditMode:(int)arg2 slot:(id)arg3;
- (id)optionForCustomEditMode:(int)arg1 slot:(id)arg2;
- (id)init;

@end

