//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>
#import "NTKRemoteComplicationBudgetManagerDelegate.h"

@interface NTKRemoteComplicationBudgetManager : NSObject
{
    id <NTKRemoteComplicationBudgetManagerDelegate> _delegate;
}

@property(nonatomic) __weak id <NTKRemoteComplicationBudgetManagerDelegate> delegate; // @synthesize delegate=_delegate;
// - (void).cxx_destruct;
- (void)removeAppBundleFromBlacklist:(id)arg1;
- (void)endMeteredSessionForAppBundleID:(id)arg1;
- (void)beginMeteredSessionForAppBundleID:(id)arg1 pid:(id)arg2 forPing:(_Bool)arg3;
- (_Bool)applicationIsForegroundForAppBundleID:(id)arg1;
- (_Bool)budgetExhaustedForAppBundleID:(id)arg1;
- (_Bool)allowsDiscretionaryWakeForAppBundleID:(id)arg1;

@end

