//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class NPSManager, NSObject;

@interface NTKTimeTravelSettings : NSObject
{
    NPSManager *_npsManager;
    _Bool _timeTravelEnabled;
    NSObject *_prefsQueue;
}

+ (id)sharedInstance;
// - (void).cxx_destruct;
- (void)_handlePrefsChanged;
- (_Bool)_isTimeTravelEnabledInPreferences;
- (_Bool)isTimeTravelEnabled;
- (void)dealloc;
- (id)init;

@end

