//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

#import <Foundation/Foundation.h>
#import "NTKAVListing.h"

@class NSString, NTKPhotoAnalysis, NTKVideo, UIImage;

@interface NTKTimelapseListing : NSObject <NSCopying, NTKAVListing>
{
    NTKVideo *_video;
    UIImage *_image;
    NSString *_videoName;
    NSString *_imageName;
    NTKPhotoAnalysis *_photoAnalysis;
    unsigned int _theme;
    int _videoIndex;
}

@property(readonly, nonatomic) NTKPhotoAnalysis *photoAnalysis; // @synthesize photoAnalysis=_photoAnalysis;
@property(readonly, nonatomic) int videoIndex; // @synthesize videoIndex=_videoIndex;
@property(readonly, nonatomic) unsigned int theme; // @synthesize theme=_theme;
// - (void).cxx_destruct;
- (void)discardAssets;
- (_Bool)snapshotDiffers:(id)arg1;
@property(readonly, nonatomic) UIImage *image;
@property(readonly, nonatomic) NTKVideo *video;
- (void)_setHasAssets;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithTheme:(unsigned int)arg1 videoIndex:(int)arg2 photoAnalysis:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

