//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@interface NTKVictoryColorPalette : NSObject
{
}

+ (id)_primaryColor;
+ (_Bool)colorHasWhiteElements:(unsigned int)arg1;
+ (id)_grayColor;
+ (id)_offWhiteColor;
+ (id)digitalComplicationsColorForColor:(unsigned int)arg1;
+ (id)analogDotColorForColor:(unsigned int)arg1;
+ (id)analogComplicationsColorForColor:(unsigned int)arg1;
+ (id)secondHandColorForColor:(unsigned int)arg1;
+ (id)platterColor;
+ (id)handsAndLogoColorForColor:(unsigned int)arg1;
+ (id)numbersColorForColor:(unsigned int)arg1;

@end

