//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//
#import <Foundation/Foundation.h>

@interface WorldClockPreferences : NSObject

- (id)cities;
- (bool)defaultCitiesAdded;
- (id)defaultsKeys;
- (id)lastModified;
- (void)setCities:(id)arg1;
- (void)setDefaultCitiesAdded:(bool)arg1;
- (void)setLastModified:(id)arg1;
- (bool)synchronize;

@end

@interface WorldClockManager : NSObject {
    NSMutableArray * _cities;
    WorldClockPreferences * _defaults;
    bool  _dirty;
    NSDate * lastModified;
}

@property (nonatomic, readonly) NSArray *cities;
@property (nonatomic, retain) NSDate *lastModified;

+ (id)sharedManager;
+ (id)sharedManagerWithPreferences:(id)arg1;

//- (void).cxx_destruct;
- (void)_notifyNano;
- (unsigned long long)addCity:(id)arg1;
- (void)addDefaultCitiesIfNeeded;
- (bool)canAddCity;
- (bool)checkIfCitiesModified;
- (id)cities;
- (id)cityWithIdUrl:(id)arg1;
- (id)fixUpCityProperties:(id)arg1;
- (id)initWithPreferences:(id)arg1;
- (id)lastModified;
- (void)loadCities;
- (void)moveCityFromIndex:(unsigned long long)arg1 toIndex:(unsigned long long)arg2;
- (void)pushCityPropertiesToPreferences;
- (void)removeAllCities;
- (void)removeCity:(id)arg1;
- (void)removeCityAtIndex:(unsigned long long)arg1;
- (void)saveCities;
- (void)setLastModified:(id)arg1;
- (id)worldClockCityFromPersistenceArray:(id)arg1;
- (id)worldClockCityFromPersistenceDictionary:(id)arg1;
- (id)worldClockCityFromPersistenceRepresentation:(id)arg1;

@end

@interface WorldClockManager (NTKAdditions)
@property(readonly, nonatomic) NSArray *ntk_cities;
@end

